<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ATMECSBLRLT-216" ignored="0" name="SampleTest" tests="1" failures="1" timestamp="11 Sep 2022 19:03:43 GMT" time="22.843" errors="0">
  <testcase name="firstTest" time="22.661" classname="com.atmecs.qa.SampleProject.testscript.SampleRegistrationTestScript">
    <failure type="java.lang.AssertionError" message="Unexpected error, please check with URL Connection timed out: connect">
      <![CDATA[java.lang.AssertionError: Unexpected error, please check with URL Connection timed out: connect
at com.atmecs.falcon.automation.ui.selenium.Browser.validateURL(Browser.java:543)
at com.atmecs.falcon.automation.ui.selenium.Browser.openURL(Browser.java:380)
at com.atmecs.qa.SampleProject.testscript.SampleRegistrationTestScript.firstTest(SampleRegistrationTestScript.java:21)
at com.atmecs.qa.SampleProject.runner.TestNGRunner.main(TestNGRunner.java:78)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
at java.lang.Thread.run(Thread.java:745)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- firstTest -->
</testsuite> <!-- SampleTest -->
